[workspace]

members = [ 
"babelfont-rs",
"designspace",
"dschecker",
"fonticulus",
"fonttools-cli",
"fonttools-rs",
"openstep-plist",
"otmath",
"otspec",
"otspec_macros",
"triangulate",
"ufo-cu2qu",
"ufo-decompose"
]

